毕业项目源码和数据库/201817380120杨磊1/Account/Controllers/RoleMenuController.cs
using Account.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Account.Controllers
{
    public class RoleMenuController : Controller
    {

        AccountDBEntities db = new AccountDBEntities();

        // GET: RoleMenu
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 删除操作的菜单
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        public ActionResult RoleDelete(int ID)
        {
            //获得角色菜单表信息
            R_Role_Menus RoleMenus = db.R_Role_Menus.Find(ID);
            db.R_Role_Menus.Remove(RoleMenus);
            db.SaveChanges();
            return RedirectToAction("Index","Role");
        }

        /// <summary>
        /// 设置操作菜单
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        public ActionResult RoleSet(int ID)
        {
            //获得角色信息
            Roles role = db.Roles.Find(ID);
            ViewBag.role = role;

            //获得角色菜单信息
           List< R_Role_Menus> roleMenus = db.R_Role_Menus.Where(p=>p.RoleID== ID).ToList();
            ViewBag.roleMenus = roleMenus;

            //获得所有菜单
            List<Menus> menu = db.Menus.ToList();
            ViewBag.menu = menu;
            return View();
        }

        [HttpPost]
        public ActionResult RoleSet(int menuid, int[] menu)
        {

            //将跟menuid有关的菜单删除
            List<R_Role_Menus> roleMenus = db.R_Role_Menus.Where(p => p.MenuID == menuid).ToList();
            foreach (var item in roleMenus)
            {
                db.R_Role_Menus.Remove(item);
            }
            db.SaveChanges();

            //添加新的菜单角色关系
            if (menu != null)
            {
                foreach (var item in menu)
                {
                        R_Role_Menus r_Role_Menus = new R_Role_Menus()
                        {
                            MenuID = item,
                            RoleID = menuid
                        };

                    db.R_Role_Menus.Add(r_Role_Menus);
                }
                db.SaveChanges();
            }
            return RedirectToAction("Index", "Role");
        }

    }
}

毕业项目源码和数据库/201817380120杨磊1/Account/Views/RoleMenu/RoleSet.cshtml
@{
    ViewBag.Title = "RoleSet";
}



@using Account.Models;
@{
    Account.Models.Roles role = ViewBag.role;
    List<R_Role_Menus> roleMenus = ViewBag.roleMenus;
    List<Menus> menu = ViewBag.menu;

}

<h2>RoleSet---@role.Name 角色的设置</h2>


@using (Html.BeginForm("RoleSet", "RoleMenu", new { @class = "form-horizontal" }))
{

    foreach (var item in menu)
    {
        var check = false;
        foreach (var item2 in roleMenus)
        {
            if (item.ID == item2.MenuID)
            {
                check = true;
            }

        }
        <input type="checkbox" value="@item.ID" checked="@check" name="menu" id="menu" />
        @item.Name
        <br />
    }

    <input type="hidden" name="menuid" value="@role.ID" />
    <input type="submit" value="提交" class="btn btn-primary" />
}