毕业项目源码和数据库/201817380120杨磊1/Account/Models/Departments.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Account.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departments
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Departments()
        {
            this.UserInfos = new HashSet<UserInfos>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string Remark { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserInfos> UserInfos { get; set; }
    }
}

毕业项目源码和数据库/201817380120杨磊1/Account/Controllers/DepartmentController.cs
using Account.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Account.Controllers
{
    public class DepartmentController : Controller
    {

        AccountDBEntities db = new AccountDBEntities();

        // GET: Department
        public ActionResult Index(string Name = "")
        {
            List<Departments> list = db.Departments.Where(p => p.Name == "" || p.Name.Contains(Name)).ToList();
            @ViewBag.name = Name;
            return View(list);
        }

        public ActionResult Add(Departments dep)
        {
            db.Departments.Add(dep);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult DepartmentsUpdate(int ID)
        {
            Departments dep = db.Departments.Find(ID);
            ViewBag.dep = dep;

            db.SaveChanges();
            return View();
        }

        [HttpPost]
        public ActionResult DepartmentsUpdate(Departments dep)
        {
            db.Entry(dep).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult DepartmentsDelete(int DepartmentID)
        {
            var rURList = db.UserInfos.Where(p => p.DepartmentID == DepartmentID).ToList();
            if (rURList.Count > 0)
            {
                return Content("<script>alert('该部门有用户不能删除');history.go(-1)</script>");
            }
            else
            {
                Departments dep = db.Departments.Find(DepartmentID);
                db.Departments.Remove(dep);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

毕业项目源码和数据库/201817380120杨磊1/Account/Views/Department/DepartmentsUpdate.cshtml
@{
    ViewBag.Title = "DepartmentsUpdate";
}

<h2>DepartmentsUpdate</h2>

<ul class="breadcrumb">
    <li><a href="">首页</a></li>
    <li><a href="">部门管理</a></li>
    <li class="active"><a href="">部门修改</a></li>
</ul>
<h2>部门修改</h2>
@using Account.Models;
@{
    Departments dep = ViewBag.dep;
}

@using (Html.BeginForm("DepartmentsUpdate", "Department", FormMethod.Post, new { @class = "form-horizontal" }))
{

    <div class="form-group">
        <label class="control-label">名称：</label>
        <input type="text" name="Name" value="@dep.Name" class="form-control" />

    </div>
    <div class="form-group">
        <label>描述：</label>
        <input type="text" name="Remark" value="@dep.Remark" class="form-control" />
    </div>
    <div>
        <a href="javascript:history.go(-1)">返回</a>
        <input type="submit" value="提交" class="btn btn-primary" />
    </div>

}

毕业项目源码和数据库/201817380120杨磊1/Account/Views/Department/Index.cshtml
@{
    ViewBag.Title = "Index";
}

@using Account.Models;
@model List<Departments>

<ul class="breadcrumb">
    <li><a href="">首页</a></li>
    <li class="active"><a href="">部门管理</a></li>
</ul>

<h2>Department--部门列表</h2>

<div class="row">

    <div class="col-lg-8">
        <form method="post" action="Add" class="form-inline">
            <label for="deparment">请输入:</label>
            <input type="text" name="Name" class="form-control" placeholder="请输入部门名称" />
            <input type="text" name="Remark" class="form-control" placeholder="请输入备注" />
            <input type="submit" value="添加" class="btn btn-primary" />
        </form>
    </div>

    <div class="col-lg-4">
        <form method="post" action="" class="form-inline">
            <label for="deparment">部门名称:</label>
            <input type="text" name="Name" id="Name" value="@ViewBag.name" class="form-control" />
            <input type="submit" value="搜索" class="btn btn-primary" />
        </form>
    </div>

</div>

<br />

<table class="table table-bordered table-condensed table-hover">
    <thead>
        <tr>
            <th>编号</th>
            <th>名称</th>
            <th>备注</th>
            <th>该部门人员</th>
            <th>该部门人数</th>
            <th>修改</th>
            <th>删除</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.ID</td>
                <td>@item.Name</td>
                <td>@item.Remark</td>
                <td>
                    @foreach (var item1 in item.UserInfos)
                    {
                        @item1.Name<br />
                    }
                </td>
                <td>@item.UserInfos.Count()</td>
                <td><a href="/Department/DepartmentsUpdate/@item.ID">修改</a></td>
                <td><a href="/Department/DepartmentsDelete?DepartmentID=@item.ID">删除</td>
            </tr>
        }
    </tbody>
</table>