毕业项目源码和数据库/201817380120杨磊1/Account/Models/UserInfos.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Account.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserInfos()
        {
            this.R_User_Roles = new HashSet<R_User_Roles>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public Nullable<int> DepartmentID { get; set; }
        public Nullable<bool> Sex { get; set; }
        public string Account { get; set; }
        public string Pwd { get; set; }
        public string Photo { get; set; }
        public string Remark { get; set; }
    
        public virtual Departments Departments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<R_User_Roles> R_User_Roles { get; set; }
    }
}

毕业项目源码和数据库/201817380120杨磊1/Account/Controllers/UserInfoController.cs
using Account.Models;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Account.Controllers
{
    public class UserInfoController : Controller
    {

        AccountDBEntities db = new AccountDBEntities();

        // GET: UserInfo
        /// <summary>
        /// 
        /// </summary>
        /// <param name="departmentID">部门ID</param>
        /// <param name="Name">用户名</param>
        /// <param name="pageIndex">当前页</param>
        /// <param name="pageCount">每页显示的行数</param>
        /// <returns></returns>
        public ActionResult Index(int departmentID = 0,string Name="",int pageIndex=1,int pageCount=5)
        {
            //获得部门下拉框部门的值
            List<Departments> dlist=  db.Departments.ToList();
            //ViewBag传递数据
            ViewBag.dlist = dlist;


            //获得总行数
            int totalCount = db.UserInfos.OrderBy(p => p.ID)
                .Where(p => (departmentID == 0 || p.DepartmentID == departmentID) && (Name == "" || p.Name.Contains(Name)))
                .Count();


            //获得总页数=总行数/页面数       Ceiling--向上取整  
            double totalPage = Math.Ceiling(totalCount / (double)pageCount);

            //查询列表信息 ----可以用OrderBy主键正序排列，条件过滤，转成集合
            //where()---调价筛选，Tolist()---转成集合 
            //Skip()--跳过指定数量的元素，返回剩下的集合,Take() --从剩下的集合数中，从第一条开始获取指定数量的集合
            List<UserInfos> list = db.UserInfos.OrderBy(p=>p.ID)
                .Where(p=>(departmentID == 0||p.DepartmentID== departmentID) && (Name==""||p.Name.Contains(Name)))
                .Skip((pageIndex-1)*pageCount).Take(pageCount)
                .ToList();

            //数据加载的同时将条件存储并输出在对应控件显示
            ViewBag.departmentID = departmentID;
            ViewBag.name = Name;


            ViewBag.pageIndex = pageIndex;    //当前页
            ViewBag.pageCount = pageCount;    //每页行数
            ViewBag.totalCount = totalCount;  //总行数
            ViewBag.totalPage = totalPage;    //总页数

            return View(list);    //用过模型传递数据
        }

       /// <summary>
       /// 添加一个用户信息
       /// </summary>
       /// <returns></returns>
        public ActionResult Insert()
        {

            //动态获取下拉框部门的值
            List<SelectListItem> list = db.Departments.Select(p => new SelectListItem()
            {
                Text = p.Name,
                Value = p.ID.ToString()

            }).ToList() ;

            ViewBag.Department = list;

            //获取多选框角色的值
            List<Roles> roles = db.Roles.ToList();
            ViewBag.roles = roles;

            return View();
        }

        [HttpPost]
        public ActionResult Insert(HttpPostedFileBase Photo, UserInfos userInfo, List<int> roles)
        {
            //-----添加图片
            //判断图片是否为空
            if (Photo != null)
            {
                //判断图片大小
                if (Photo.ContentLength>0 && Photo.ContentLength<4194304)
                {
                    //获取上传路径
                    string FileName= Path.GetFileName(Photo.FileName);
                    //获取文件后缀名
                    string suff = FileName.Substring(FileName.IndexOf(".") + 1);

                    //判断格式
                    if (suff =="jpg" || suff=="png" || suff=="gif")
                    {
                        //图片存储位置
                        Photo.SaveAs(Server.MapPath("~/images/users/"+ Photo.FileName));
                        userInfo.Photo = Photo.FileName;
                    }
                  
                }

            }
            else
            {
                return Content("<script>alert('未获取到上传的文件')</script>");
            }
            //-----添加用户信息
            db.UserInfos.Add(userInfo);
            db.SaveChanges();

            //-----添加用户与角色的关系
            //遍历所选中的角色
            foreach (var item in roles)
            {
                //new 一个新的 R_User_Roles对象，将角色ID 与 RoleID 组成一个新的对象添加
                R_User_Roles UR = new R_User_Roles() {

                    UserID =userInfo.ID,
                    RoleID=item
                };
                db.R_User_Roles.Add(UR);
            }
          
            db.SaveChanges();
            return RedirectToAction("Index");
                
        }

        /// <summary>
        /// 修改用户信息
        /// </summary>
        /// <param name="ID"></param>
        /// <returns></returns>
        public ActionResult Update(int ID)
        {

           //动态获取下拉框部门的值
            List<Departments> departmentlist = db.Departments.ToList();
            ViewBag.dptlist = departmentlist;

            //获取多选框角色的值
            List<Roles> Role = db.Roles.ToList();
            ViewBag.role = Role;


            //1、获得UseInfo信息
            UserInfos userInfo = db.UserInfos.Find(ID);
            ViewBag.userInfo = userInfo;

            //2、通过用户id查到--对应的角色关系。并存ViewBag 中
            List<R_User_Roles> UserRole = db.R_User_Roles.Where(p => p.UserID == ID).ToList();
            ViewBag.UserRole = UserRole;

            return View();
        }


        [HttpPost]
        public ActionResult Update(HttpPostedFileBase EPhoto, UserInfos userInfo, List<int> roles)
        {

            //------1、判断是否重新添加图片
            if (EPhoto !=null)
            {
                //判断图片大小
                if (EPhoto.ContentLength > 0 && EPhoto.ContentLength < 4194304)
                {
                    //获取上传路径
                    string FileName = Path.GetFileName(EPhoto.FileName);
                    //获取文件后缀名
                    string suff = FileName.Substring(FileName.IndexOf(".") + 1);

                    //判断格式
                    if (suff == "jpg" || suff == "png" || suff == "gif")
                    {
                        //图片存储位置
                        EPhoto.SaveAs(Server.MapPath("~/images/users/" + EPhoto.FileName));
                        userInfo.Photo = EPhoto.FileName;
                    }

                }
            }
            //----2、修改用户信息--Modified看你这条记录中是否有数据发生改变
            db.Entry(userInfo).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();

            //-----3、修改用户与角色的关系

            //先通过用户ID清除与该用户id的相关角色关系
            List<R_User_Roles> urInfo = db.R_User_Roles.Where(p => p.UserID == userInfo.ID).ToList();

            foreach (var item in urInfo)
            {
                db.R_User_Roles.Remove(item);
            }
            db.SaveChanges();


            //添加新的关系--遍历所选中的角色
            foreach (var item in roles)
            {
                //new 一个新的 R_User_Roles对象，将角色ID 与 RoleID 组成一个新的对象添加
                R_User_Roles r_User_Roles = new R_User_Roles()
                {

                    UserID = userInfo.ID,
                    RoleID = item
                };
                db.R_User_Roles.Add(r_User_Roles);
            }
            db.SaveChanges();

            return RedirectToAction("Index");
        }
         /// <summary>
         /// 删除
         /// </summary>
         /// <param name="UserID"></param>
         /// <returns></returns>
        public ActionResult Remove(int UserID)
        {
            //查出用户角色关系表
            var rURList = db.R_User_Roles.Where(p => p.UserID == UserID).ToList();
            if (rURList.Count > 0)
            {
                return Content("<script>alert('该用户有角色不能删除');history.go(-1)</script>");
            }
            else
            {
                UserInfos user = db.UserInfos.Find(UserID);
                db.UserInfos.Remove(user);
                db.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

毕业项目源码和数据库/201817380120杨磊1/Account/Views/UserInfo/Index.cshtml
@{
    ViewBag.Title = "Index";
}

@*-----------------------面包屑导航-----------------*@
<br />
<ul class="breadcrumb">
    <li><a href="#">首页</a></li>
    <li class="active">用户管理</li>
</ul>


<h2>UserInfo--用户列表</h2>

@using Account.Models
@model List<UserInfos>

@*---------------------------------------------顶部-----------------------------*@
<div class="row">
    <div class="col-lg-6">
        @Html.ActionLink("新增", "Insert", "UserInfo", null, new { @class = "btn btn-primary" })
        @Html.ActionLink("导入", "Add", "UserInfo", null, new { @class = "btn btn-primary" })
        @Html.ActionLink("批量删除", "Add", "UserInfo", null, new { @class = "btn btn-primary" })
    </div>
    <div class="col-lg-6">
        <form method="post" action="" class="form-inline">

            <label class="label1" for="department">部门:</label>
            <select name="departmentID" id="departmentID" class="form-control">
                <option value="0">===请输入===</option>
                @foreach (var item in ViewBag.dlist)
                {
                    if ((item.ID).Equals(ViewBag.departmentID))
                    {
                        <option value="@item.ID" selected>@item.Name</option>
                    }
                    else
                    {
                        <option value="@item.ID">@item.Name</option>
                    }

                }
            </select>

            <label class="label2" for="department">姓名:</label>
            <input type="text" name="Name" class="form-control" value="@ViewBag.name" placeholder="请输入姓名模糊查询" />

            <input type="submit" value="查询" class="btn btn-primary" />
        </form>

    </div>
</div>

<br />

@*---------------------------------------------内容区域显示-----------------------------*@
<table class="table table-bordered table-condensed table-hover">
    <tr>
        <th>编号</th>
        <th>姓名</th>
        <th>部门</th>
        <th>性别</th>
        <th>账号</th>
        <th>密码</th>
        <th>照片</th>
        <th>备注</th>
        <th>账号拥有的角色</th>
        <th>设置角色</th>
        <th>删除</th>
        <th>修改</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
            <td>@item.ID</td>
            <td>@item.Name</td>
            <td>@item.Departments.Name</td>                @*一对一关系直接主键取值*@
            <td>
                @if (item.Sex == true)
                {
                    @:男
                }
                else
                {
                    @:女
                }
            </td>
            <td>@item.Account</td>
            <td>@item.Pwd</td>
            <td>
             
                <img src="~/images/users/@item.Photo" style="width:50px;height:50px" />

            </td>
            <td>@item.Remark</td>
            <td>
                @foreach (var item1 in item.R_User_Roles)
                {
                    @item1.Roles.Name <a href="/UserRole/Delete/@item1.ID" onclick="return confirm('你确定要删除嘛')"><span class="glyphicon glyphicon-remove" aria-hidden="true"></span></a><br /> @*一对多关系 循环拿值*@
                }
            </td>
            <td><a href="/UserRole/setRole?UserID=@item.ID">设置角色</a></td>
            <td><a href="/UserInfo/Remove?UserID=@item.ID">删除</a></td>
            <td><a href="/UserInfo/Update/@item.ID">修改</a></td>
            
        </tr>


    }
</table>


@*---------------------分页-----------------*@
<div class="row">

    <div class="col-lg-8 form-inline">
        <label>总共 @ViewBag.totalCount</label>&nbsp;
        <label>选择显示的行数：</label>
        <select name="pageCount" id="pageCount" class="form-control " onchange="window.location = this.value;">
            @{
                int[] count = new int[] { 5, 10, 20, 30, 40 };
            }
            @foreach (var item in count)
            {
                //如果数组==页面数，则显示你所选择的，否则显示默认的
                if (item.Equals(ViewBag.pageCount))
                {
                    <option selected value="/UserInfo/Index?departmentID=@ViewBag.departmentID&Name=@ViewBag.name&pageIndex=1&pageCount=@item">@item</option>
                }
                else
                {
                    <option value="/UserInfo/Index?departmentID=@ViewBag.departmentID&Name=@ViewBag.name&pageIndex=1&pageCount=@item">@item</option>
                }

            }
        </select>
    </div>

    <div class="col-lg-4">
        <nav aria-label="Page navigation example">
            <ul class="pagination">
                @*----首页----*@
                <li class="page-item"><a class="page-link" href="/UserInfo/Index?departmentID=@ViewBag.departmentID&Name=@ViewBag.name&pageIndex=1&pageCount=@ViewBag.pageCount">首页</a></li>

                @*-------上一页---，如果当前页面>1 则可以上一页，否则禁用上一页按钮---*@
                @if (ViewBag.pageIndex > 1)
                {
                    <li class="page-item"><a href="/UserInfo/Index?departmentID=@ViewBag.departmentID&Name=@ViewBag.name&pageIndex=@(ViewBag.pageIndex-1 )&pageCount=@ViewBag.pageCount">上一页</a></li>
                }
                else
                {
                    <li class="page-item disabled"><a class="page-link" href="#">上一页</a></li>
                }

                @*-----------显示当前页面-----------*@
                <li class="page-item "><a class="page-link" href="#">@ViewBag.pageIndex</a></li>

                @*-------下一页---，如果当前页面<页面总数 则可以下一页，否则禁用下一页按钮---*@
                @if (ViewBag.pageIndex < ViewBag.totalPage)
                {
                    <li class="page-item"><a class="page-link" href="/UserInfo/Index?departmentID=@ViewBag.departmentID&Name=@ViewBag.name&pageIndex=@(ViewBag.pageIndex+1)&pageCount=@ViewBag.pageCount">下一页</a></li>
                }
                else
                {
                    <li class="page-item disabled"><a class="page-link" href="#">下一页</a></li>
                }

                @*------------末页，当前页面==总页面数-------*@
                <li class="page-item"><a class="page-link" href="/UserInfo/Index?departmentID=@ViewBag.departmentID&Name=@ViewBag.name&pageIndex=@ViewBag.totalPage&pageCount=@ViewBag.pageCount">末页</a></li>
            </ul>
        </nav>
    </div>
</div>

毕业项目源码和数据库/201817380120杨磊1/Account/Views/UserInfo/Insert.cshtml
@{
    ViewBag.Title = "Insert";
}

<h2>Insert--添加一个用户信息</h2>

@using (Html.BeginForm("Insert", "UserInfo", FormMethod.Post, new { @class = "form-horizontal" ,enctype = "multipart/form-data" }))
{

    <div class="form-group">
        <label class="control-label">姓名:</label>
        @Html.TextBox("Name", null, new { @class = "form-control" })
    </div>

    <div class="form-group">
        <label class="control-label">部门:</label>
        @Html.DropDownList("DepartmentID", ViewBag.Department as List<SelectListItem>, new { @class = "form-control" })
    </div>

    <div class="form-group">
        <label for="Sex" class="control-label">性别:</label>
        @Html.RadioButton("Sex", "true", isChecked: true)男
        @Html.RadioButton("Sex", "false")女
    </div>


    <div class="form-group">
        <label class="control-label">账号:</label>
        @Html.TextBox("Account", null, new { @class = "form-control" })
    </div>

    <div class="form-group">
        <label class="control-label">角色:</label>

        @foreach (var item in ViewBag.roles)
        {
            @*@Html.CheckBox("R_User_Roles", new { @class = "checkbox-inline " }) @item.Name*@
            <input type="checkbox" value="@item.ID" name="roles" id="roles" /> @item.Name
        }

    </div>


    <div class="form-group">
        <label class="control-label">密码:</label>
        @Html.Password("Pwd", null, new { @class = "form-control" })
    </div>

    <div class="form-group">
        <label class="control-label">图片:</label>
        <input type="file" value="请选择图片" name="Photo" id="Photo"/>
       
    </div>

    <div class="form-group">
        <label class="control-label">备注:</label>
        @Html.TextArea("Remark", null, new { @class = "form-control" })
    </div>


    <div>
        <a href="javascript:history.go(-1)">返回</a>
        <input type="submit" value="保存" class="btn btn-primary" />
    </div>
}

毕业项目源码和数据库/201817380120杨磊1/Account/Views/UserInfo/Update.cshtml
@{
    ViewBag.Title = "Update";
}

<h2>Update</h2>


@using Account.Models
@{ 
    UserInfos userInfo = ViewBag.userInfo;

}

<form action="/UserInfo/Update" method="post">

    <input type="hidden" id="ID" name="ID" value="@userInfo.ID" />

    <div class="form-group">
        <label>姓名：</label>
        <input type="text" name="Name" class="form-control" value="@userInfo.Name" />
    </div>

    <div class="form-group">
        <label>部门：</label>
        <select class="form-control" name="DepartmentID">
            @*<option value="@userInfo.DepartmentID">@userInfo.Departments.Name</option>*@

            @foreach (var item in ViewBag.dptlist)
            {
                if (userInfo.DepartmentID == item.ID)
                {
                    <option value="@item.ID" selected>@item.Name</option>
                }

                <option value="@item.ID">@item.Name</option>
            }

        </select>
    </div>

    <div class="form-group">
        <label>性别：</label>

        @if (@userInfo.Sex == true)
        {
            <input type="radio" name="Sex" value="true" checked="checked" /> @:男
            <input type="radio" name="Sex" value="false" /> @:女
        }
        else
        {
            <input type="radio" name="Sex" value="true" checked="checked" /> @:男
            <input type="radio" name="Sex" value="false" checked="checked" /> @:女
        }

    </div>

    <div class="form-group">
        <label>账号：</label>
        <input type="text" name="Account" class="form-control" value="@userInfo.Account" />
    </div>

    <div class="form-group">
        <label class="control-label">角色:</label>

        @foreach (var item in ViewBag.role)
        {
            var check = false;
            foreach (var item2 in ViewBag.UserRole)             /*遍历角色关系表*/
            {
                if (item.ID == item2.RoleID)
                {
                    check = true;
                    break;
                }

            }

            <input type="checkbox" value="@item.ID" checked="@check" name="roles" id="roles" />
            @item.Name
            <br />

        }
    </div>

    <div class="form-group">
        <label>密码：</label>
        <input type="password" name="Pwd" class="form-control" value="@userInfo.Pwd" />
    </div>

    <div class="form-group">
        <label class="control-label">图片:</label>
        <img src="~/images/users/@userInfo.Photo" style="width:50px ;height:50px" />

        @*保留该用户以前的图片*@
        <input type="hidden" name="Photo" id="Photo" value="@userInfo.Photo" />
        @*提供修改，在选择的图片*@
        <input type="file" value="请选择图片" name="EPhoto" id="Ehoto" />

    </div>

    <div class="form-group">
        <label>备注：</label>
        <textarea name="Remark" class="form-control" value="@userInfo.Remark">@userInfo.Remark</textarea>
    </div>

    <div>
        <a href="javascript:history.go(-1)">返回</a>
        <input type="submit" value="保存" class="btn btn-primary" />
    </div>

</form>